apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: atziluth-org-tls
spec:
  secretName: atziluth-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: atziluth.org
  dnsNames:
    - atziluth.org
    - www.atziluth.org
